version: '3.8'

services:
  # SemWare AI service
  semware:
    image: ghcr.io/rishikanthc/semware:v0.1.0
    container_name: zendown-semware
    ports:
      - "8000:8000"
    volumes:
      - ./semware-db:/db
    environment:
      - SEMWARE_API_KEY=test-api-key-12345
    restart: unless-stopped
    networks:
      - zendown-network

  # ZenDown application
  zendown:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    container_name: zendown
    ports:
      - "8080:8080"
    environment:
      # SemWare API Key - must match the one set in SemWare service
      - SEMWARE_API_KEY=test-api-key-12345
      # SemWare URL - points to the SemWare service within the Docker network
      - SEMWARE_URL=http://semware:8000
    volumes:
      # Persist database files
      - ./data:/app/data
      # Persist attachment files
      - ./attachments:/app/attachments
    restart: unless-stopped
    depends_on:
      - semware
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/notes"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - zendown-network

networks:
  zendown-network:
    name: zendown-network
    driver: bridge 