version: "3.9"

services:
  zendown-ai:
    image: ghcr.io/rishikanthc/zendown-ai:v0.1.0
    ports:
      - "8000:8000"
    volumes:
      - ./db:/db # This volume is for zendown-ai's own database
    # environment:
    #   - LANCEDB_URI=/db
    restart: unless-stopped

  zendown:
    image: ghcr.io/rishikanthc/zendown:v0.1.3
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    #   network: host
    #   args:
    #     - DATABASE_URL=file:local.db 
        # - AI_SERVER_URL=http://zendown-ai:8000
    ports:
      - "3000:3000"
    volumes:
      - ./zendown_db_data:/db # Mount the named volume for the database
    environment:
      - AI_SERVER_URL=http://zendown-ai:8000
      # - DATABASE_URL=file:/data/local.db 
    depends_on:
      - zendown-ai
    restart: unless-stopped

volumes:
  zendown_db_data: {} # Define the named volume for zendown's database

